export const jobApplications = [
  {
    title: 'Global Program Manager',
    company: 'Stripe',
    url: 'https://linkedin.com',
    countries: ['Ireland', 'US'],
    dateApplied: new Date('2026-04-05'),
    status: 'not started',
    progress: 'awaiting response',
    tags: [],
  },
  {
    title: 'Senior Product Manager',
    company: 'Linear',
    url: 'https://linear.app',
    countries: ['Remote'],
    dateApplied: new Date('2026-04-20'),
    status: 'applied',
    progress: 'recruiter screening',
    tags: [],
  },
  {
    title: 'Engineering Manager',
    company: 'Vercel',
    url: 'https://vercel.com',
    countries: ['Remote'],
    dateApplied: new Date('2026-05-01'),
    status: 'interviewing',
    progress: 'interview',
    tags: [],
  },
  {
    title: 'Product Manager',
    company: 'Anthropic',
    url: 'https://anthropic.com',
    countries: ['US', 'Remote'],
    dateApplied: new Date('2026-05-15'),
    status: 'applied',
    progress: 'recruiter screening',
    tags: [],
  },
]
